- hosts: dev-server
  tasks:
    - name: Start docker service
      command: sudo service docker start
      ignore_errors: yes

    - name: register all docker containers id are running
      command: sudo docker ps -aq
      register: dockerContainerIds

    - name: register all current docker images id
      command: sudo docker images -aq
      register: dockerImagesIds

    - name: Stop all containers
      command: "sudo docker stop {{dockerContainerIds.stdout}}"
      ignore_errors: yes

    - name: Remove all containers
      command: "sudo docker rm {{dockerContainerIds.stdout}}"
      ignore_errors: yes

    - name: Remove all images
      command: "sudo docker rmi --force {{dockerImagesIds.stdout}}"
      ignore_errors: yes

    - name: Log out if connected to Docker
      command: sudo docker logout
      ignore_errors: yes

    - name: Log in to my Dockerhub
      command: sudo docker login -u "s3758780" -p "Ducanh113" docker.io

    - name: Build images based on current Dockerfile
      command: sudo docker build -t apache-image:latest .

    - name: Tag image to current image docker hub
      command: sudo docker tag apache-image:latest s3758780/apache-3758780:latest

    - name: Push to docker hub
      command: sudo docker push s3758780/apache-3758780:latest

    - name: register all current docker images id
      command: sudo docker images -aq
      register: dockerImagesIds

    - name: Remove all images
      command: "sudo docker rmi --force {{dockerImagesIds.stdout}}"
      ignore_errors: yes

    - name: Run the apache container based on pushed docker hub image
      command: sudo docker run -d --name apache-container --rm -p 8080:80 s3758780/apache-3758780:latest
